version: '3.8'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask_server
    ports:
      - "5000:5000"
    networks:
      - webnet

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - FLASK_API_URL=http://flask_server:5000
    depends_on:
      - flask
    networks:
      - webnet

networks:
  webnet:
