version: '3.8'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask_server
    environment:
      # Define your own FINNHUB_API_KEY. Do not put quotes.
      - FINNHUB_API_KEY=
    ports:
      - "5000" # Accessible within container
    networks:
      - webnet

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    container_name: nextjs_app
    ports:
      - "3000:3000" # Accessible inside and outside container
    environment:
      - FLASK_API_URL=http://flask_server:5000
      - DATABASE_URL=file:./main.db
      - NEXTAUTH_URL=http://localhost:3000 # Hosted locally. Else, change to canonical URL of site.

      # Define your own SECRET_KEY and NEXTAUTH_SECRET. These are examples. Do not put quotes.
      - SECRET_KEY=Y2vMqaWcy4xeb9XXhz60A6mnEJSmg1UTwYxvd7skffg=
      - NEXTAUTH_SECRET=fQ+x+mFRfqOiDpAxdJGqDiTU+6yJ47ooTJWKa+vHFek=
    depends_on:
      - flask
    networks:
      - webnet
    volumes:
      - ./prisma:/prisma


networks:
  webnet:
